version: "3.8"

services:
  classification_api:
    container_name: classification_api
    build:
      context: classification_api
    volumes:
      - ./classification_api/:/app
      - ./mount:/mnt
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8002:8000
    restart: always
    runtime: nvidia
