version: "3.8"

services:
  classification_api:
    container_name: classification_api
    build:
      context: classification_api
    volumes:
      - ./classification_api/:/app
      - ./mount:/mnt
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8002:8000
    restart: always
    runtime: nvidia

  backend:
    container_name: backend
    build:
      context: backend
    volumes:
      - ./backend/:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8003:8000
    restart: always

  db:
    container_name: db
    image: postgres
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    restart: always

volumes:
  db:
    external: false
